// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjrK_N_AIV7r4z0ewZ59VKvtH4UdGrsKM',
    appId: '1:49514259492:web:a9113b2a6c8ec51f3524b1',
    messagingSenderId: '49514259492',
    projectId: 'visionary-ai-36658',
    authDomain: 'visionary-ai-36658.firebaseapp.com',
    storageBucket: 'visionary-ai-36658.firebasestorage.app',
    measurementId: 'G-S4KM46XE53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgoi8ACFBEzUTQuPwZyr4EWVTB-AgaocY',
    appId: '1:49514259492:android:c5552edc9223d5703524b1',
    messagingSenderId: '49514259492',
    projectId: 'visionary-ai-36658',
    storageBucket: 'visionary-ai-36658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdasEzfAMDp-QuUwAlhwltVfrR9OzW0YE',
    appId: '1:49514259492:ios:cca7293defbe518b3524b1',
    messagingSenderId: '49514259492',
    projectId: 'visionary-ai-36658',
    storageBucket: 'visionary-ai-36658.firebasestorage.app',
    iosBundleId: 'com.example.visionaryAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdasEzfAMDp-QuUwAlhwltVfrR9OzW0YE',
    appId: '1:49514259492:ios:cca7293defbe518b3524b1',
    messagingSenderId: '49514259492',
    projectId: 'visionary-ai-36658',
    storageBucket: 'visionary-ai-36658.firebasestorage.app',
    iosBundleId: 'com.example.visionaryAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjrK_N_AIV7r4z0ewZ59VKvtH4UdGrsKM',
    appId: '1:49514259492:web:05cea1c51e881c573524b1',
    messagingSenderId: '49514259492',
    projectId: 'visionary-ai-36658',
    authDomain: 'visionary-ai-36658.firebaseapp.com',
    storageBucket: 'visionary-ai-36658.firebasestorage.app',
    measurementId: 'G-HJRF16YP7N',
  );
}
